apiVersion: v1
kind: Service
metadata:
  name: customer-service-new
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
    - name: grpc
        port: 9090
        targetPort: 9090
  selector:
    app: customer-service-new
