apiVersion: v1
kind: Service
metadata:
  name: customer-service-new
spec:
  type: ClusterIP
  ports:
    - name: "customer-service-new"
      port: 8083
      targetPort: 8083
  selector:
    app: customer-service-new
