apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service-new
  template:
    metadata:
      labels:
        app: customer-service-new
    spec:
      containers:
        - image: mariiamarafiievych/customer-service-new
          name: customer-service-new
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
